# Generated by Django 3.2 on 2023-06-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_titlegenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlegenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='titlegenre',
            old_name='title_id',
            new_name='title',
        ),
    ]
